### ISSUE TITLE
Bigger pets!

### ISSUE THREAD

**Issue by pzelnip** [tonybaloney/vscode-pets#1]
My cat is so tiny, can't we have an option to make the pet bigger?

**Comment by tonybaloney** [comment]
Very good point, I tend to agree. I'll have to think about scaling up the graphics without making them blurry.

**Comment by ZurMaD** [comment]
keep calm, they grow like in  reality

**Comment by kyranet** [comment]
> Very good point, I tend to agree. I'll have to think about scaling up the graphics without making them blurry.

I found something in [StackOverflow](https://stackoverflow.com/questions/7615009/disable-interpolation-when-scaling-a-canvas), which seems to work nicely 😉

**Comment by tonybaloney** [comment]
Updated in 0.6.0. Options for `petSize` are `nano`, `medium` and `large`. It will use `nano` by default so that the pets are consistent with the existing size

**Comment by pzelnip** [comment]
Love it, thanks for implementing!
