### ISSUE TITLE
Type and color of pet don't change

### ISSUE THREAD

**Issue by Lizardoman** [tonybaloney/vscode-pets#100]
Hello to whoever is reading this,
Whenever I try to change the type or the color of my pet, the sprite glitches and disappears for half a second or so, and then reappears just the same as before. 
Therefore I can't change the type nor the color of my pet.  
I encounter this problem ever since I ran the extension for the first time. 
Does anyone have/did have the same problem? If so, how did you work it out?

**Comment by Harry-Hopkinson** [comment]
Could you share a video that highlights your issue? I was not able to replicate it.

**Comment by Lizardoman** [comment]
I fixed it.
I closed the panel and opened another one once I changed the color and type.
Have a nice end of the day.

**Comment by Harry-Hopkinson** [comment]
To you too.

**Comment by MariaSolOs** [comment]
@Harry-Hopkinson Could I take this? It makes sense to restart the session when the pet type/color changes :)
