### ISSUE TITLE
Deleting pets

### ISSUE THREAD

**Issue by novemberkid11** [tonybaloney/vscode-pets#102]
Hello,
I am unable to remove pets in the 1.10.0 version. Also, one "pet" (I genuinely don't know which one it's supposed to be) looks like an image icon and runs around (it's the default now and I cannot change it to anything else). How could I fix this? I tried uninstalling and installing it again, I ran it a couple of times, the version 1.9.0 worked fine restarting the whole thing also doesn't do anything. I really love this extension and I'd love to fix it.
Thank you
<img width="163" alt="vscode pets issue" src="https://user-images.githubusercontent.com/104679041/166103649-dd38163c-fe24-47d9-b3e9-3f1bdc101c71.png">

**Comment by Harry-Hopkinson** [comment]
We fixed this issue but it is not in the current release. In the next release this issue will be fixed.

**Comment by novemberkid11** [comment]
That's awesome. Thank you very much!

**Comment by Harry-Hopkinson** [comment]
@tonybaloney this issue can be fixed.
