### ISSUE TITLE
Can you have the explorer section get smaller

### ISSUE THREAD

**Issue by IanAMacMillan** [tonybaloney/vscode-pets#103]
When I have the explorer section selected, the dog only uses the bottom part of the section it would be nice to be able to make the window smaller by moving down the top. This makes sense when there is no theme on.

 Also, it would be cool if the dog slept more often. It would be cool to just look down and see my sleeping dog :)

Love the package! It is great!

**Comment by tonybaloney** [comment]
![screenshot 2022-11-22 at 12 59 49](https://user-images.githubusercontent.com/1532417/203198735-eb553919-fcf3-4b68-ba25-c4162cfb00dc.gif)
This is as small as you can make it. You can also click+drag the window around
