### ISSUE TITLE
add brighter backgrounds! 

### ISSUE THREAD

**Issue by tarazoelee** [tonybaloney/vscode-pets#109]
Would love to see a cute field for the pets to play in or something bright and colorful.

**Comment by muuvmuuv** [comment]
Yeah that would match my light theme pretty well :D

**Comment by tonybaloney** [comment]
![Hills](https://user-images.githubusercontent.com/1532417/194463726-1f1d2332-d527-42d8-af36-92dfe3c8b921.png)

I tried a beach theme as well (needs scaling) which works well with light themes

<img width="1279" alt="screenshot 2022-10-07 at 15 02 05" src="https://user-images.githubusercontent.com/1532417/194465730-50a28942-4319-4c9b-837b-32fdec626b00.png">
