### ISSUE TITLE
Feisty snake? 🐍

### ISSUE THREAD

**Issue by algcifaldi** [tonybaloney/vscode-pets#11]
Hi there! On the [VScode Marketplace](https://marketplace.visualstudio.com/items?itemName=tonybaloney.vscode-pets) it mentions a feisty snake, but it seems like this is not currently supported.

Would this be a good candidate for open source contributors to help out with? If so I would be interested! Apologies as I know this really isn't an "issue"

<img width="787" alt="Screen Shot 2021-03-08 at 1 28 05 PM" src="https://user-images.githubusercontent.com/3019807/110384188-272d9f00-8012-11eb-8f62-6f643f1e443b.png">

**Comment by arronhunt** [comment]
He shows up for me in the settings 🤔 

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/298336/110389724-c7d38d00-8019-11eb-8993-8be24ce09d97.png">

**Comment by algcifaldi** [comment]
_gasp_, thank you so much! sorry I missed it!
