### ISSUE TITLE
Who wants to addopt?

### ISSUE THREAD

**Issue by EstyBrandes** [tonybaloney/vscode-pets#111]
Hi there, I'm having some difficulities with erasing added animals. I had my duck, just wanted to see the other animals, but I can't delete them. I couldn't find a way to reset the settings, even after uninstalling, after shutting down my computer, after reseting everything that I could - nothing, I can understand they want a home, but I can't afford all those animals at my workspace. 
Help me with deleting the animals. 
Thank you :)

**Comment by Harry-Hopkinson** [comment]
There are no commands that delete pets, but there is a reset pets command.

**Comment by EstyBrandes** [comment]
It does nothing to the pets, I've tried it all

**Comment by Harry-Hopkinson** [comment]
Can you show a video?

**Comment by EstyBrandes** [comment]
https://user-images.githubusercontent.com/95626359/172875392-5b045224-c9c0-4b5e-83ea-790c68a895c4.mp4

I've tried it all. All the resets I found in the app, tried to uninstall and install again, tried to exit VScode and enter again. nothing

**Comment by EstyBrandes** [comment]
It worked, but now it won't let me chose again something that is not the default cat hahaa

**Comment by tonybaloney** [comment]
To change the default pet, you have to go to preferences, look for the vscode-pets settings and change the pet.
