### ISSUE TITLE
How can I add the pets without the panel?

### ISSUE THREAD

**Issue by rrdlpl** [tonybaloney/vscode-pets#117]
The panel takes up too much space and I actually want to see the pets running on my code. :)

**Comment by Valenwe** [comment]
+1 !

**Comment by DigitalJokerMan** [comment]
+1, feels pointless to allocate screen space for the pet.

**Comment by tonybaloney** [comment]
I know everyone wants this feature, it's been requested many, many, times! 

But it's not possible to implement in the VS Code extension API. The pets must be inside a panel, extensions cannot render graphics onto the code editor.

**Comment by Valenwe** [comment]
Hmmm I see...
Is there ways to render it in other pre existing panels? Like file explorer, or little nav bar on the top or the bottom?

**Comment by tonybaloney** [comment]
nope.
