### ISSUE TITLE
Spamming the throw-ball button increases speed of the ball.

### ISSUE THREAD

**Issue by Koratsama** [tonybaloney/vscode-pets#119]
When clicking the throw-ball button repeatedly on the explorer view of vs code pets, the speed of the ball increases each time until a pet has caught the ball. The ball jumps around really quickly after hitting the button multiple times in succession. 

![image](https://user-images.githubusercontent.com/14094188/181121000-027b3924-531f-4183-8814-7e292ac7912c.png)

This also seems to confuse the pets? they sometimes run back and forth not going towards the ball

**Comment by tonybaloney** [comment]
Fixed in main
