### ISSUE TITLE
Error while spawning pet

### ISSUE THREAD

**Issue by Valenwe** [tonybaloney/vscode-pets#120]
If I change the extension's settings Position from Panel to Explorer, 
I am now unable to spawn any pet, displaying me the error 'Cannot read properties of undefined (reading 'webview')'

**Comment by Harry-Hopkinson** [comment]
Working on this error now.

**Comment by abigmiu** [comment]
it seems not work 

![image](https://user-images.githubusercontent.com/43983920/193176852-4338d4d9-bc36-4ee2-803d-471604774a50.png)

vscode version 
```
版本: 1.71.2
提交: 74b1f979648cc44d385a2286793c226e611f59e7
日期: 2022-09-14T21:05:37.721Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 20.6.0
沙盒化: No
```




extension version 
![image](https://user-images.githubusercontent.com/43983920/193176964-65a9bf90-5d31-4958-ad8d-2a6915194c06.png)

**Comment by tonybaloney** [comment]
> it seems not work
> 
> ![image](https://user-images.githubusercontent.com/43983920/193176852-4338d4d9-bc36-4ee2-803d-471604774a50.png)
> 
> vscode version
> 
> ```
> 版本: 1.71.2
> 提交: 74b1f979648cc44d385a2286793c226e611f59e7
> 日期: 2022-09-14T21:05:37.721Z
> Electron: 19.0.12
> Chromium: 102.0.5005.167
> Node.js: 16.14.2
> V8: 10.2.154.15-electron.0
> OS: Darwin x64 20.6.0
> 沙盒化: No
> ```
> 
> extension version ![image](https://user-images.githubusercontent.com/43983920/193176964-65a9bf90-5d31-4958-ad8d-2a6915194c06.png)

What steps did you do to make this error appear?

**Comment by tonybaloney** [comment]
Ah I see now, yes if you have the explorer mode set and the pets panel not visible, then you cannot send commands (like delete all pets) to the view. I will update the error to be more meaningful.
