### ISSUE TITLE
Add white-colored dogs

### ISSUE THREAD

**Issue by 0xNike** [tonybaloney/vscode-pets#121]
I'm guessing most of us are using a dark-themed VS Code. Having black / brown dogs makes it hard to see. Can we add white as an option? Also, my Westie dog passed away recently, would be nice if the white dog is a Westie ❤️

**Comment by tonybaloney** [comment]
I'm so sorry to hear that. I'll see what I can do

**Comment by tonybaloney** [comment]
@0xNike Checkout #124 to see previews

**Comment by tonybaloney** [comment]
![screenshot 2022-08-08 at 17 06 24](https://user-images.githubusercontent.com/1532417/183359564-59099373-1c15-490e-8484-59b572ce97ee.gif)
here's a screenshot from inside the panel

**Comment by 0xNike** [comment]
@tonybaloney so sorry I just saw this! I LOVE IT!!! THANK YOU ANTONY ❤️  You've made my day 🥲
