### ISSUE TITLE
Trouble downloading

### ISSUE THREAD

**Issue by mattleew123** [tonybaloney/vscode-pets#123]
Hey sorry to bother you I've been trying to download the extension for an hour now. When I try to look it up on the vs extensions it doesn't show up and when I try to download it manually by double clicking on the file I still can't get it to work. Is there any way I can download it still? I would love to your extension would bring me so much joy.
<img width="709" alt="Screenshot 2022-08-05 225425" src="https://user-images.githubusercontent.com/100065006/183236254-cdffcbf8-bdbc-4934-81de-74f7a505884a.png">
<img width="329" alt="Screenshot 2022-08-05 225537" src="https://user-images.githubusercontent.com/100065006/183236292-c5870554-4e00-4996-9804-2e60f6dd4177.png">

**Comment by Harry-Hopkinson** [comment]
The extension is only for Visual Studio Code, not Visual Studio.
