### ISSUE TITLE
Panel vs. explorer

### ISSUE THREAD

**Issue by littlepurpleflower** [tonybaloney/vscode-pets#130]
I'm having issues with running my pet into the explorer. 

At some point, I deleted the spawning cat and now I have an empty explorer VS code drop down. When I spawn a new pet (through prompt or by manually clicking +), it opens a new panel and loads the pet. Regardless of the explorer setting I have, it always loads in a panel. 

When I go to delete pets from the new panel that is open, I have to go into settings, change explore setting back to panel then delete the pets I do not want. 

Strangely enough, when the setting is in explore, while I can't load a pet, I can throw a ball in the explore. This only works using the setting in the explore bar. When I use the prompt, it throws it in the panel.  When I change the background with the explore setting marked, it changes it in the explore. 

I uninstalled and reinstalled; I can't get the base cat back. I uninstalled and deleted cached data, I can't get the base cat back. 

Short of uninstalling VS Code, I'm unsure how to solve the problem.

**Comment by tonybaloney** [comment]
Did this issue always exist or has it just started recently?

**Comment by littlepurpleflower** [comment]
This is my first time using VS pets. So, recently, I suppose. 

As of now, only the panel behaves properly. I can't get any animal to spawn in the explorer.

**Comment by tonybaloney** [comment]
I've pushed a patch 1.13.1 that fixes the bug with spawning pets. 

When testing, I could set the background and throw the ball using both the explorer and the panel.

Let me know if there are any remaining issues once you've updated

**Comment by littlepurpleflower** [comment]
It works now, thanks!
