### ISSUE TITLE
[ ERROR ] - Unable to Remove All Pets

### ISSUE THREAD

**Issue by LanguageXange** [tonybaloney/vscode-pets#135]
I tried to run the command "Remove all pets" but the command seems not found
See attached screenshot

![Command-Error](https://user-images.githubusercontent.com/23568340/192885101-41bd9461-2a7e-475c-94d7-ed47449c437f.png)

To remove all pets, I had to run the command "Remove pet" several times ( it gave me a dropdown menu of pets currently in the panel )

**Comment by Harry-Hopkinson** [comment]
I fixed this in #133, just waiting for it to be merged.

**Comment by tonybaloney** [comment]
Please update the extension to 1.13.2, it might take a few hours for it appear in the Extensions Panel
