### ISSUE TITLE
We need Tamagotchi sytle activites.

### ISSUE THREAD

**Issue by FurkanEdizkan** [tonybaloney/vscode-pets#137]
Tamagotchi style activities can be cool to have, this extension can be great relaxing time game.

- Feed pets
- Pet animals
- Interact with them

**Comment by Luke-G-Cordova** [comment]
Is there a branch or fork for this already? Id like to help if I can!

**Comment by tonybaloney** [comment]
No there isn't, but if you want to contribute features that'd be great!

**Comment by Luke-G-Cordova** [comment]
Sounds good, I have a pull request right now and am definitely thinking about contributing more. I think this project is a cool fun idea!
