### ISSUE TITLE
Not compatible with current (v 1.52) of vscode

### ISSUE THREAD

**Issue by carlandthehumancrab** [tonybaloney/vscode-pets#14]
![Capture](https://user-images.githubusercontent.com/35293790/110867623-f7ef8a00-82be-11eb-827c-5a481ad14176.PNG)

**Comment by tonybaloney** [comment]
The current version of vscode is 1.54. This extension works with 1.53 and above. 

You'll need to update vscode before installing. The good news is those newer versions come with lots of new features!
