### ISSUE TITLE
Command 'vscode-pets-delete-pets' not found  🐈‍⬛  🐍 🐩 ❌

### ISSUE THREAD

**Issue by leereilly** [tonybaloney/vscode-pets#140]
Hi there -  I experience the following error when I enter <kbd>⌘</kbd> <kbd>SHIFT</kbd> <kbd>P</kbd> and select `Pet Coding: Remove all pets` 🔎 

![Screen Shot 2022-09-29 at 9 39 25 AM](https://user-images.githubusercontent.com/121322/193089492-9ffaa911-0012-4420-a5e6-2d38526d0aab.png)

This is using GitHub Codespaces if that's relevant here.

**Comment by kbluescode** [comment]
Replicated without Codespaces on M1 Mac
<img width="1690" alt="image" src="https://user-images.githubusercontent.com/11985485/193117639-7cc30c3f-05e0-4fe9-b8e5-fe5d06f57931.png">

**Comment by kbluescode** [comment]
Looks like there's a fix in https://github.com/tonybaloney/vscode-pets/pull/133

**Comment by tonybaloney** [comment]
Please update the extension to 1.13.2, it might take a few hours for it appear in the Extensions Panel
