### ISSUE TITLE
Hacktoberfest contributions

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/vscode-pets#143]
Hello!

This project is open to hacktoberfest contributors. 

## Easy to start with contributions

- What about adding some [additional pet names](https://github.com/tonybaloney/vscode-pets/blob/master/src/common/names.ts)?
- What about improving the instructions in the README?
- Are there any [open issues](https://github.com/tonybaloney/vscode-pets/labels/help%20wanted) you can fix?

## Drawings and Animations

If you want to contribute improvements to the animations, additional pet colors or even new pets, clone the repository and work in the `media/` folder.

Most drawings are done in [aseprite](https://www.aseprite.org) you can edit the GIFs directly. Animations should be 8 frames per second. The style of the extension is to have pixelated creatures (although not limited to an 8-bit color canvas).

Don't worry if you don't have enough coding experience to add the changes to the extension to support the new animations, we can help you with that.

## Translations

Speak a language other than English? We have some [translation issues](https://github.com/tonybaloney/vscode-pets/issues?q=is%3Aissue+is%3Aopen+label%3Atranslations) up for grabs

## Code contributions

You'll need to clone and open this project in VS Code. 

Run `npm run compile` to recompile the extension and then launch it from the Debug panel in VS Code.

**Comment by amitanshusahu** [comment]
### i would like to work on this 
can i get this assigned ..  😄

**Comment by tonybaloney** [comment]
> ### i would like to work on this 
> 
> can i get this assigned ..  😄  
> 
> @tonybaloney 

This is more of a list of possible things you can do. If you want to work on one of those, raise a separate issue with what you're doing then a PR linked to it 👍🏻

**Comment by kev-odin** [comment]
Hello @tonybaloney 

I was wondering if using another FOSS to support the pixel art component would be viable. Something like using [Pixelorama](https://github.com/Orama-Interactive/Pixelorama). Is there a list of behaviors that need to be animated? I was not able to find this in the readme.md

**Comment by tonybaloney** [comment]
> Hello @tonybaloney
> 
> I was wondering if using another FOSS to support the pixel art component would be viable. Something like using [Pixelorama](https://github.com/Orama-Interactive/Pixelorama). Is there a list of behaviors that need to be animated? I was not able to find this in the readme.md

You can use any tool to make the animations, as long as they are at 8 frame-per-second and in the pixelated style used in the extension. The minimum set of behaviours is:

- standing
- walking
- running/chasing
- holding green ball
