### ISSUE TITLE
Remove "un-cat" like names from names.ts

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/vscode-pets#148]
See https://github.com/tonybaloney/vscode-pets/blob/master/src/common/names.ts#L1

**Comment by Mannuel25** [comment]
Hello @tonybaloney , I'd love to work on this issue. But, could you please clarify what you mean by `un-cat like names`

**Comment by tonybaloney** [comment]
I copied the list of dog and cat names. So some of the cat names are things like Baxter, which is a dog name

**Comment by Mannuel25** [comment]
Oh, now it's clear. I will remove whichever name that's not a cat's. Kindly assign this to me, I'd like to work on it.

**Comment by slayeh17** [comment]
Hey @Mannuel25 if you need some help, I'll gladly do it cause I also want to work on this.😊

**Comment by tonybaloney** [comment]
I suggest one of you does dogs and the other does cats

**Comment by Mannuel25** [comment]
Okay, I'll do the dogs, while @slayeh17 handles the cats.

**Comment by tonybaloney** [comment]
Someone has already submitted a PR. So this one is taken now. I'll put more ideas in the backlog. Submitted PRs come first unfortunately

**Comment by Mannuel25** [comment]
Oooops, okay. Thank you
