### ISSUE TITLE
Remove "un-dog" like names from list

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/vscode-pets#149]
See DOG_NAMES in https://github.com/tonybaloney/vscode-pets/blob/master/src/common/names.ts#L1

**Comment by slayeh17** [comment]
Hey @tonybaloney what if I remove some names which are dog-like?😅 I mean some names seem to me un-dog like but they might seem to you dog-like.

**Comment by tonybaloney** [comment]
Go for it 👍🏻
