### ISSUE TITLE
Verify that the index of all pet names is sequential

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/vscode-pets#161]
Write a test that goes through each list of pet names and verifies that the index (the first part of the map) is sequential.

OR write a better map that doesn't require numeric indexes

**Comment by vydyas** [comment]
@tonybaloney  can you assign this bug to me. As part of hacktoberfest I'll fix this.

1. Assign the bug
2. I'll raise PR in 2 days
3. job done

**Comment by vydyas** [comment]
@tonybaloney  can you merge you pull request. There is no test setup in master branch.

**Comment by tonybaloney** [comment]
Is now merged

**Comment by ccjmne** [comment]
@vydyas I don't know if you've started working on this, but I suggest we opt for

> OR write a better map that doesn't require numeric indexes

... if possible! I think the code would be leaner and simpler :)

**Comment by ccjmne** [comment]
Hey @vydyas, @tonybaloney,

It seems there hasn't been much progress on this issue.
I'd be happy to take it on, if I'm not treading on anybody's toes :)

I have some time today and I already looked into this issue when implementing custom names for pets!

**Comment by ccjmne** [comment]
Hey @vydyas, @tonybaloney,

It's been over two weeks since there last was any activity here.
I'd love to take over this issue and get it done :)

Please don't hesitate to let me know if I can get it sorted, without stepping on anybody's toes!

**Comment by vydyas** [comment]
@tonybaloney  I got sick can you assign this issue to someone. Sorry for late information

**Comment by ccjmne** [comment]
@vydyas Aw, sorry to hear that. I hope you'll get better soon!
No worries about the delay, we're all in the same community, just having fun building silly things :)
Cheers!
