### ISSUE TITLE
Allow customisation of colours for clippy

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/vscode-pets#17]
It would be great to have clippy in the "officially" supported colours by clippy wearing different colored baseball caps.

The cap should also have the VS Code logo on it 👍 

@marcduiker do you think this would be a lot of work?

**Comment by marcduiker** [comment]
I'll do some experimentation. Clippy is very low res though (on purpose) so having the VSCode logo on the cap is unlikely. I'll definitely try colored baseball caps. You want all the colors from the PetColor enum right?

**Comment by marcduiker** [comment]
![image](https://user-images.githubusercontent.com/4191277/111286734-cb32ce00-8642-11eb-8c09-71ec4ea3e3c7.png)

Brown, black, and green caps. Shall I continue and re-export the animations with these caps?

**Comment by tonybaloney** [comment]
Looks amazing ❤️
