### ISSUE TITLE
When not choosing a color, a pet with no image is spawned

### ISSUE THREAD

**Issue by SanderRonde** [tonybaloney/vscode-pets#179]
First of all I want to say that I love this extension. 

## The bug

When spawning a pet but not choosing a color (pressing escape), a pet with the missing-image image is spawned.

To reproduce:
- Run `Pet coding: spawn additional pet`
- Choose `cat`
- Press escape

Then a pet with the missing-image image is walking around
![image](https://user-images.githubusercontent.com/5385012/193887303-f2d9c2cd-ed61-4ead-8cc4-afebc0ae3473.png)

**Comment by Harry-Hopkinson** [comment]
I will look at this
