### ISSUE TITLE
Pets tend to overlap when moving around

### ISSUE THREAD

**Issue by jailbreakerVC** [tonybaloney/vscode-pets#180]
![image](https://user-images.githubusercontent.com/54243183/194092912-0c591aca-1a1f-41d8-b976-1b823824e777.png)
Duck and crab are basically stuck together

**Comment by tonybaloney** [comment]
They get assigned a random position, I think it was an unlucky coincidence that they spawned next to each other.

A potential improvement would be to space out the pets when setting up the panel

**Comment by tonybaloney** [comment]
<img width="132" alt="screenshot 2022-10-07 at 13 18 51" src="https://user-images.githubusercontent.com/1532417/194452977-0b4c9592-31f6-4955-8763-e5325cefb60a.png">
I've got the same thing, its really annoying. I think adding an element of randomness to their speed would spread them out naturally

**Comment by tonybaloney** [comment]
Related #183

**Comment by systemoutprintlnhelloworld** [comment]
it seems this question not solve yet for some reason(as shown in the pic,this three animal moving in a same speed(althogh dog and cat moving faster than snake but they constantly moving forward and backward)
![image](https://github.com/tonybaloney/vscode-pets/assets/62531937/1ef28998-f940-4a4a-a516-9df18635a452)
![image](https://github.com/tonybaloney/vscode-pets/assets/62531937/7643fa11-56c7-4cbb-a709-caee5c9e4d3c)
