### ISSUE TITLE
pet walking in separate flap

### ISSUE THREAD

**Issue by meudeustadeu** [tonybaloney/vscode-pets#181]
![image](https://user-images.githubusercontent.com/71295557/194322118-47e16100-ad0a-4f92-864e-50c3eb9fab31.png)

hello, I loved the extension, I really want to use it, but I'm not getting it anymore, after making a configuration, the pet no longer walks all over the screen, but through a separate tab according to the print.

**Comment by jyorien** [comment]
Did you want the pet to be on the left panel like here?
![image](https://user-images.githubusercontent.com/58991251/194480287-ab1ae843-2bed-4d6a-8fe6-514fc6d8bba9.png)

If so, you can: <br>
1. Go to Extensions ![image](https://user-images.githubusercontent.com/58991251/194480491-baf34f84-8bd6-4e54-a218-f3152e06937d.png) on the left panel <br> 
2. Click the Gear icon > Extension Settings <br> ![image](https://user-images.githubusercontent.com/58991251/194480580-6f81eadd-b77a-452a-98e4-6ee11248a873.png) <br>
3.  Set this setting to 'Explorer'
![image](https://user-images.githubusercontent.com/58991251/194480862-b651ada2-e907-4289-9c30-120e7a3f49a0.png)

**Comment by tonybaloney** [comment]
See #250
