### ISSUE TITLE
Add a random modifier (+/- 30%) to pet speed

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/vscode-pets#183]
In order to randomise the speed of pets, the speed (0-5) should be randomised by +/- 30%.

For example, when the pet speed is PetSpeed.normal (3) then a pet speed could be 

3.13, 3.04, 2.95, 3.25

Speed of 0 should still be 0, because this is the rock, which cannot move.

https://github.com/tonybaloney/vscode-pets/blob/fb11781940662b58f862b7b613794d14ce3e0b39/src/panel/pets.ts#L224

**Comment by jyorien** [comment]
hi i would like to work on this:)

**Comment by tonybaloney** [comment]
Great!
