### ISSUE TITLE
Add a custom message for cat

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/vscode-pets#185]
Replace the existing message with something better for this pet

https://github.com/tonybaloney/vscode-pets/blob/58a4b6d61a5373babeb4a1b750dfa9b26645375f/src/panel/pets.ts#L591-L594

**Comment by gulyapulya** [comment]
Hello @tonybaloney, this is my first Hacktoberfest and I would love to work on this issue! Also, wanted to mention that the general idea of the project is also so fun and cool... One question, should the new message be for or from a cat pet?

**Comment by tonybaloney** [comment]
@gulyapulya sure you can work on this issue. 

The message is from the pet, so replace `says hello !` with something that a cat might say :-)

**Comment by tonybaloney** [comment]
@gulyapulya please tell me how you found this repository on github?

**Comment by gulyapulya** [comment]
@tonybaloney I was looking through the issues with "Hacktoberfest" label and focused on the repos with at least a few starts and found this one. I have not used or known this this extension but I quickly checked out the README and generally the code and the idea looked very cool to me. Plus, the code organization is really nice and easy to navigate, thanks for that. I personally use VScode and this looks interesting to have for fun while coding.
