### ISSUE TITLE
Add a custom message for dog

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/vscode-pets#186]
Replace the existing message with something better for this pet

https://github.com/tonybaloney/vscode-pets/blob/58a4b6d61a5373babeb4a1b750dfa9b26645375f/src/panel/pets.ts#L658-L661

**Comment by Aman0307** [comment]
@tonybaloney I would like to contribute to this issue.

**Comment by tonybaloney** [comment]
All yours @Aman0307

**Comment by Aman0307** [comment]
@tonybaloney this message is from our side to the dog right?? We are saying hello to the dog??

**Comment by tonybaloney** [comment]
Message is from the dog to us. So "woof" would be a good start.

**Comment by Aman0307** [comment]
How about this??
Every dog has its day - and today is woof day! Today I just want to bark.

**Comment by Aman0307** [comment]
@tonybaloney I have made a PR. Please merge.
