### ISSUE TITLE
Add a custom message for clippy

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/vscode-pets#188]
Replace the existing message with something better for this pet

https://github.com/tonybaloney/vscode-pets/blob/58a4b6d61a5373babeb4a1b750dfa9b26645375f/src/panel/pets.ts#L764-L767

**Comment by akk312000** [comment]
Can I take this issue @tonybaloney ?

**Comment by tonybaloney** [comment]
Yep!
