### ISSUE TITLE
Add a custom message for duck

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/vscode-pets#190]
Replace the existing message with something better for this pet

https://github.com/tonybaloney/vscode-pets/blob/58a4b6d61a5373babeb4a1b750dfa9b26645375f/src/panel/pets.ts#L813-L816

**Comment by akk312000** [comment]
Would love to work on this issue

**Comment by tonybaloney** [comment]
Sure!

**Comment by tonybaloney** [comment]
Completed in #206
