### ISSUE TITLE
Add a custom message for crab

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/vscode-pets#192]
```
        // TODO: Add a custom message for crab
```

https://github.com/tonybaloney/vscode-pets/blob/58a4b6d61a5373babeb4a1b750dfa9b26645375f/src/panel/pets.ts#L911-L914

**Comment by akk312000** [comment]
Can I give this a try? @tonybaloney

**Comment by tonybaloney** [comment]
Sure!
