### ISSUE TITLE
Add a custom message for zappy

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/vscode-pets#193]
```
        // TODO: Add a custom message for zappy
```

https://github.com/tonybaloney/vscode-pets/blob/58a4b6d61a5373babeb4a1b750dfa9b26645375f/src/panel/pets.ts#L960-L963

**Comment by Aman0307** [comment]
@tonybaloney I would like to contribute to this issue

**Comment by Aman0307** [comment]
@tonybaloney what is zappy???
Which animal??

**Comment by tonybaloney** [comment]
The lightning bolt. It's a mascot for Azure Functions

**Comment by tonybaloney** [comment]
Completed by #207
