### ISSUE TITLE
Add a custom message for rock

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/vscode-pets#194]
```
        // TODO: Add a custom message for rock
```

https://github.com/tonybaloney/vscode-pets/blob/58a4b6d61a5373babeb4a1b750dfa9b26645375f/src/panel/pets.ts#L991-L994

**Comment by mehraankush** [comment]
what kind of message

**Comment by tonybaloney** [comment]
Whatever a rock might say instead of "hello"

**Comment by mehraankush** [comment]
ok i'll try that

**Comment by Harikrishna3** [comment]
What would happen if it said, "I always rocks"?

**Comment by Harikrishna3** [comment]
Or "Yo Yo its rock"
