### ISSUE TITLE
more clippy

### ISSUE THREAD

**Issue by deltadan** [tonybaloney/vscode-pets#2]
i need clippy in my code please...

**Comment by Favna** [comment]
This would a really funny addition. If Microsoft won't give us Clippy, lets put Clippy in the Microsoft editor.

**Comment by marcduiker** [comment]
I've created a fork and will add an pixel version of Clippy in the next couple of days 😁.

**Comment by marcduiker** [comment]
See pull/15

**Comment by tonybaloney** [comment]
implemented in #15 thanks @marcduiker
