### ISSUE TITLE
Cuter snake

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/vscode-pets#24]
The snake resolution is too low and it lacks character. You can barely see its eyes.

If anyone wants to contribute a cuter snake it would be welcome :heart:

**Comment by marcduiker** [comment]
Well, I can't ignore this one 😅. I'll make some drawings.

**Comment by marcduiker** [comment]
Basics are done, now working on animations.
![Python_vscode_pets_still_idle2](https://user-images.githubusercontent.com/4191277/115141073-c5ae1680-a03a-11eb-8d3a-714d033a4b18.png)
