### ISSUE TITLE
Adding a chicken as a new pet🐔

### ISSUE THREAD

**Issue by MhouneyLH** [tonybaloney/vscode-pets#242]
I am missing my favourite pet - the chicken, so I would like to add it. 

I think of like a grain-picking animation, after the chicken was spawned. In additition it should jump and then slowly flies down to the bottom again. 
One problem I will have is to design the chicken in a pixel-art way. Is there anyone who could deal with this or should I just use the art of other people?

**Comment by gulyapulya** [comment]
I made these two, one for idle state and one for picking grain. I followed some videos on youtube with real chickens to see how they move to imitate their real behaviour. Took me some time to figure out as I am not an animator, but looks decent to me. 
![chicken](https://user-images.githubusercontent.com/52351598/205839841-da5c3ff9-1584-4854-a4d1-fe02e488ad3d.gif)
![chicken](https://user-images.githubusercontent.com/52351598/205839863-0fec1e12-40ac-4823-8c5e-ae3b5fb374cd.gif)

**Comment by MhouneyLH** [comment]
These two animations are looking awesome. (of course you can modify my chicken-design 😊)

Following animations would fit in my opinion:
1. idle
2. normal walking
3. holding the green ball
4. sprinting when the ball is thrown
5. grain picking
6. flap their wings

The first four animations are mandatory as mentioned in [this](https://github.com/tonybaloney/vscode-pets/blob/master/docs/source/contributing.rst) file.

**Comment by gulyapulya** [comment]
Chickens do not usually chase/catch the ball, so I am not sure if these are necessary. @tonybaloney, what do you think about animations 3 and 4?

**Comment by tedbergeron** [comment]
What if the chicken sprints _away_ from the ball? Scattering when startled. (probably goes against the default programming, but might be worth a try)

**Comment by gulyapulya** [comment]
Actually, I just checked and everyone chases a ball no matter the pet type, so I will add the animations
