### ISSUE TITLE
How about a pet that can fly around and perch on your code... 

### ISSUE THREAD

**Issue by dragontheory** [tonybaloney/vscode-pets#243]
Like... a little pet dragon...

```
      .
 .>   )\;`a__
(  _ _)/ /-." ~~
 `( )_ )/
  <_  <_ 
```

Maybe it could even breath a little fire and smoke on your code. 

```
.        _.-----.  \.-./       . .
\`-.._,-' .-. .-.`-' ``-.  _,-'.'`.
 `-.____,-. `:. `.-'-._.O-:_ .:'.,|
           `-" `-"          `-.__.'
```
Makes a glyph or two disintegrate. Bad dragon! 

Of course you'd have to feed him to keep from eating your code... 

```
                    ___________________
                  / Nom nom nom nom... \
                  \___     ____________/
                      \  /
                      |/
              /   \
      )      ((   ))     (
     /|\      ))_((     /|\
    / | \    (/\|/\)   / | \
---/--|-voV---\`|'/--Vov-|--\---
        '^`   (o o)  '^`
              `\Y/'
```

Maybe a thought bubble every 5 or 10 minutes (user variable) that says... 

```
      __________________
    /  Mmm... hungry...  \
    \_     ______________/
      ( _ )
     (_)
    O
```

Then maybe a speech bubble that says... 

```
      ______________________
    /  Mmm... code... yum... \
    \___     ________________/
        \  /
        |/
```

And then users could type a few glyphs at the bottom of the editor for the little pet dragon to snack on. 

That would be fun. 

WDYT? 

_Thanks for the extension BTW!!_

**Comment by tonybaloney** [comment]
That would be cool, but due to limitations noted in #117 #4 and many other issues, it's not possible.

All graphics must live inside a panel.

**Comment by dragontheory** [comment]
Ah. Seems I'm a little late to the party. Thank you for your response and this great extension. Appreciate your hard work.
