### ISSUE TITLE
Can't run in vscode.dev

### ISSUE THREAD

**Issue by kouhe3** [tonybaloney/vscode-pets#256]
I want to use this good extension in vscode.dev

**Comment by tonybaloney** [comment]
Please provide more detail. 

Have you tried to install in vscode.dev? Does it not work? Why did it not work? Did you get an error, please provide screenshots of the error.

**Comment by kouhe3** [comment]
![image](https://user-images.githubusercontent.com/25522053/196032622-78358150-5e15-4453-af62-32a98cdb46ec.png)

Unable in vscode.dev and github.dev

**Comment by kev-odin** [comment]
![error](https://user-images.githubusercontent.com/60195141/196052764-bc490963-57b2-44dc-9ecc-750d3572c8c9.png)

**Expected/Actual Results**
I wanted to run vscode-pets in vscode.dev to play with cute pets. Extension does not work on the web version of VSCode.

**Steps to Reproduce**
I forked the repo, opened the editor with `.`, and tried to install the extension via the side panel.

**Environment**
VSCode for the web
