### ISSUE TITLE
Rust and crabs

### ISSUE THREAD

**Issue by mintyc** [tonybaloney/vscode-pets#26]
The rust language has very good ide support from vscode but use would go through the roof if a pet crab could be part of your extension.

There are lots of images of walking and dancing crabs available.

If you are interested in adding this new pet, I'd be happy to seek appropriate artwork (copyright and licensing etc.) from the rust community if you have lists of animations, image sizes and number of frame details.

**Comment by marcduiker** [comment]
Hi @mintyc,

I was already thinking of Rust and a pet crab. I can make the animations so no need to find existing artwork.
@tonybaloney single color (red) for this one as well?

**Comment by Milo123459** [comment]
+1 on this. Can't wait!

**Comment by marcduiker** [comment]
@tonybaloney  this one can be closed, has been delivered in release 1.3.0 🦀🎉
