### ISSUE TITLE
Background art too?

### ISSUE THREAD

**Issue by mintyc** [tonybaloney/vscode-pets#27]
Maybe the bottom of the editor window where the pet plays could also have a subtle background to show where they play? Could even make it animated. PetPlay themes.

This extension is going places!

**Comment by tonybaloney** [comment]
Working on this now. I'll make them configurable with different themes. Also planning to use layers so the pet will be between the background and foreground

**Comment by tonybaloney** [comment]
<img width="691" alt="Screen Shot 2021-04-15 at 4 30 50 pm" src="https://user-images.githubusercontent.com/1532417/114824311-0eca5480-9e08-11eb-8291-3a51f2884519.png">

A little prototype with a dark forest asset set. It has a background + foreground so the pets will be between the two (z-index wise)

**Comment by tonybaloney** [comment]
https://user-images.githubusercontent.com/1532417/114826640-13dcd300-9e0b-11eb-83ca-434e80f5e595.mov
