### ISSUE TITLE
Throwing second ball whilst pets are chasing causes loop in pet state

### ISSUE THREAD

**Issue by Joe676** [tonybaloney/vscode-pets#282]
I've noticed that the ball speeds up significantly after a few throws. A very fast ball makes pets spin in circles. After reset the first ball is even faster, but the next is regular speed.

**Comment by KComrade53** [comment]
I haven't been able to reproduce this on my Mac

**Comment by broem** [comment]
I can reproduce on both Windows (10  v10.0.19044 Build 19044) and Mac (Montery 12.6). 

Reproduce:
 - Spawn a pet
 - Toss a ball
 - While pet is chasing the ball throw another ball.
 - Pet starts spinning.

**Comment by amauryjaphet** [comment]
it happens  to me too

**Comment by tonybaloney** [comment]
As a workaround, close and reopen the panel. I'll investigate how it gets in that state.

**Comment by amauryjaphet** [comment]
> As a workaround, close and reopen the panel. I'll investigate how it gets in that state.

Oh ok 😊
