### ISSUE TITLE
What is theme, tell me please 🥺🥺🥺

### ISSUE THREAD

**Issue by satonin12** [tonybaloney/vscode-pets#288]
What is theme ?
what is this topic please tell me, my vscode is customized to the maximum and I would like to take something from here. Thanks a lot in advance!!

And yes, the extension is very cute!

![изображение](https://user-images.githubusercontent.com/24912294/197406338-a3ae050e-4558-4856-b6af-0dd5135346cd.png)

**Comment by MhouneyLH** [comment]
This theme is called "beach". You can use it by adjusting the "Vscode-pets: Theme"-property to "beach". :)

**Comment by MhouneyLH** [comment]
Oh, then there was a little misunderstanding on my side.

**Comment by tonybaloney** [comment]
One of the Noctis themes. Install the extension. Maybe Noctis Lilac.

**Comment by tonybaloney** [comment]
link to theme https://vscodethemes.com/e/liviuschera.noctis/noctis-lilac?language=python
