### ISSUE TITLE
Add Azure Functions Zappy as a pet

### ISSUE THREAD

**Issue by marcduiker** [tonybaloney/vscode-pets#29]
Zappy is the (unofficial) mascot for Azure Functions. I'd like to add them as pet.

See https://twitter.com/jeffhollan/status/1321876877485637633

![image](https://user-images.githubusercontent.com/4191277/111746488-64095980-888e-11eb-9997-95a7a5e7a9ac.png)

**Comment by JING1201** [comment]
Should this issue be closed? I see that Zappy is already in the extension :D
