### ISSUE TITLE
Please create a clone of this extension for IntelliJ IDEA!

### ISSUE THREAD

**Issue by naXa777** [tonybaloney/vscode-pets#291]
This is so annoying that IntelliJ IDEA Ultimate is missing such an awesome plugin that's available in VSC for free

**Comment by tonybaloney** [comment]
IDEA extensions are written in Java/Kotlin and VS Code extensions are written in TypeScript, nothing in this extension could easily be ported to IntelliJ, so this would be a big undertaking.
