### ISSUE TITLE
Cat with ball is the wrong ratio

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/vscode-pets#304]
The image gets larger when the cat catches the ball

**Comment by MrSurana** [comment]
This will give an idea of aspect ratios for all cat images, so you can fix at once.

|file|dimensions|ratio|
|:-:|:-:|:-:|
|black_fall_from_grab_8fps.gif|115x85|1.353|
|black_idle_8fps.gif|135x95|1.421|
|black_land_8fps.gif|105x75|1.4|
|black_run_8fps.gif|130x95|1.368|
|black_swipe_8fps.gif|135x95|1.421|
|black_walk_8fps.gif|115x65|1.769|
|black_walk_fast_8fps.gif|135x95|1.421|
|black_with_ball_8fps.gif|95x80|1.188|
|brown_fall_from_grab_8fps.gif|115x95|1.211|
|brown_idle_8fps.gif|135x95|1.421|
|brown_land_8fps.gif|105x75|1.4|
|brown_run_8fps.gif|135x95|1.421|
|brown_swipe_8fps.gif|135x95|1.421|
|brown_walk_8fps.gif|115x65|1.769|
|brown_walk_fast_8fps.gif|135x95|1.421|
|brown_with_ball_8fps.gif|95x80|1.188|
|white_fall_from_grab_8fps.gif|115x85|1.353|
|white_idle_8fps.gif|135x95|1.421|
|white_land_8fps.gif|105x75|1.4|
|white_run_8fps.gif|130x95|1.368|
|white_swipe_8fps.gif|135x95|1.421|
|white_walk_8fps.gif|115x65|1.769|
|white_walk_fast_8fps.gif|135x95|1.421|
|white_with_ball_8fps.gif|95x80|1.188|

**Comment by gulyapulya** [comment]
Hi @tonybaloney, let me try to solve this.

**Comment by gulyapulya** [comment]
I can see that all cat gifs with the ball have a smaller dimension which probably gets enlarged to the original size while running, can you guide me on what would be best to do?

**Comment by tonybaloney** [comment]
The images need resizing to 120px by 85px without making the cat seem stretched.

Aseprite can do this with a Canvas Resize to the following settings

<img width="829" alt="screenshot 2022-11-18 at 17 12 48" src="https://user-images.githubusercontent.com/1532417/202633612-952191e3-afa2-4393-9c95-85ea8a518849.png">

Then you'll need to start VS Code pets in development mode and let the cat catch the ball to see whether it worked. 

There will probably be some free alternatives to aseprite

**Comment by gulyapulya** [comment]
Thanks a lot for the guidelines!

**Comment by gulyapulya** [comment]
Also, as a suggestion, it might be great to create a CONTRIBUTING.md file with instructions for contributors who have little knowledge of VScode extension development and other areas to speed up their introduction to the project. :)
