### ISSUE TITLE
Add a grey cat.

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/vscode-pets#325]
There is now artwork for a grey cat. 

![cat04_dash_12fps](https://user-images.githubusercontent.com/1532417/203189882-b63ad878-f8f2-4a5f-ac00-01e60eb3e815.gif)

**Comment by tonybaloney** [comment]
![cat03_run_12fps](https://user-images.githubusercontent.com/1532417/207214794-29734034-98c9-4c91-bb00-79cf18c7c31a.gif)
and a brown cat

**Comment by tonybaloney** [comment]
@NicholasJohansan would you be interested in taking this one on as well? 🙏🏻

**Comment by NicholasJohansan** [comment]
> @NicholasJohansan would you be interested in taking this one on as well? 🙏🏻 

Sure, may I know where I can find the artwork for them?

I think there's already a brown cat, so maybe not the brown one, unless I should replace it with the new one instead (but looks weird since it looks like a completely different cat compared to the other colours).

**Comment by tonybaloney** [comment]
I’ve purchased them off the author, I can email you a zip of the originals that has the new gifs. They’ll need resizing and cropping to be the same dimensions as the other cats. 
You’ll also need to decide what colour to name the new brown cat, since brown is already taken

**Comment by NicholasJohansan** [comment]
Sure, that's fine, you can email them to me at [nicholas@nj.sg](mailto:nicholas@nj.sg)
for the new colour, is orange fine? or is that too far off from the sprite's colour.

**Comment by tonybaloney** [comment]
maybe light-brown? I've emailed the gifs. You'll need to scale them up and then crop them to the same sizes as the other cats in aseprite.

Thanks

**Comment by NicholasJohansan** [comment]
ok, will do
