### ISSUE TITLE
(Red Dog) Walk gif not named properly 

### ISSUE THREAD

**Issue by EricEnergy** [tonybaloney/vscode-pets#351]
Dog walking image is not showing 
![image](https://user-images.githubusercontent.com/51306586/207702837-5fd1daf0-72c7-48bb-a5a4-4b05fe8081d7.png)

an s is missing after 8fp and just needs to be added
![image](https://user-images.githubusercontent.com/51306586/207702742-3e14920a-0617-4f21-828b-55324e20e2ae.png)

**Comment by EricEnergy** [comment]
thanks @Harry-Hopkinson

**Comment by Harry-Hopkinson** [comment]
No problem.
