### ISSUE TITLE
Cannot install on VS Code '1.55.2'

### ISSUE THREAD

**Issue by Yiming-Miao** [tonybaloney/vscode-pets#365]
I cannot install pets on VS Code '1.55.2'. 
Plsssssss make it compatilbe with this version.

**Comment by tonybaloney** [comment]
This version is almost 2 years old. I'll support the version within a few months. I can share some link to explain how to update if you need?

**Comment by Yiming-Miao** [comment]
Could you please tell me the minimum version of VS Code to run vscode-pets? I think I should update my VS Code version:)

**Comment by tonybaloney** [comment]
1.73.0

But you should always keep vs code up to date regardless of vscode-pets :-)
