### ISSUE TITLE
Incompatibility with VS Code 1.64.2?

### ISSUE THREAD

**Issue by laurazpm** [tonybaloney/vscode-pets#368]
I've tried to install the extension but there's a (very straightforward) error saying that it is not compatible with VS Code version 1.64.2 which is the one I have.
Any ideas? I would really love to try this!

Thanks,
Laura

**Comment by Harry-Hopkinson** [comment]
The minimum version of vscode that works with vscode-pets is version 1.73.0. Can you try updating to this version?

**Comment by laurazpm** [comment]
it worked, thank you!

**Comment by Harry-Hopkinson** [comment]
No problem
