### ISSUE TITLE
Rubber duck is no longer animated

### ISSUE THREAD

**Issue by marcduiker** [tonybaloney/vscode-pets#37]
Somehow the rubber duck gifs are not playing the animation (it was in v0.11). It's currently only showing the first frame. The media files seem to be fine.

**Comment by tonybaloney** [comment]
thats weird. is it still moving around? Which state is it in?

**Comment by marcduiker** [comment]
It is still moving and state switching works. I'll re-export the gifs to check if the files have been corrupted somehow 🤷‍♂️. All the other pets work as expected.
