### ISSUE TITLE
The pet panel is in the wrong place in VS Codium

### ISSUE THREAD

**Issue by Ash-Crow** [tonybaloney/vscode-pets#373]
**Describe the bug**
I installed vscode-pets in VSCodium and started a pet coding session. The panel opens in a standard editor tab instead of the explorer panel.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/765956/213408567-af692ed6-8fc5-41c2-87dc-8349d70b0fd5.png)

**Additional context**
I'm not actually sure if this is VSCodium-related but it is the only reason I can think of for this difference in behaviour (though all the other plugins I have behave exactly like in VSCode)

VSCodium version 1.74.3 on Ubuntu 22.04.

**Comment by NicolasRenault** [comment]
Hi @Ash-Crow,
It seems you are missing the "vscode-pets: position" settings. You can in the extension settings select between "explorer" and "panel". You should just switch it and see if it's working properly !
![image](https://user-images.githubusercontent.com/59968905/215222978-5df6d018-8963-426f-8291-b602c75805cf.png)

**Comment by Ash-Crow** [comment]
That was it, thanks!

I think it should be added to the documentation

**Comment by NicolasRenault** [comment]
Glad it helps ! 

I'll take a look to add it to the documentation.
