### ISSUE TITLE
No puedo abrir los temas 

### ISSUE THREAD

**Issue by javier25arroyo** [tonybaloney/vscode-pets#378]
Cuando coloco en la paleta de comandos vscode-pets.theme no aparecen resultados

**Comment by tonybaloney** [comment]
vscode-pets.theme es un ajuste de configuración. 
<img width="1021" alt="screenshot 2023-02-06 at 09 23 18" src="https://user-images.githubusercontent.com/1532417/216849323-d66522f5-4aaa-490b-ac26-aed859f738af.png">
