### ISSUE TITLE
Add pet size small 

### ISSUE THREAD

**Issue by AndreasWintherMoen** [tonybaloney/vscode-pets#379]
**Please describe your idea.**
The nano option is too small and medium is too large. Something in between would be perfect!

**Describe how the idea would be helpful**
More options > fewer options

**Additional context**
I'm willing to implement it myself and submit a PR.

**Comment by tonybaloney** [comment]
Please submit a PR.

- Update the `PetSize` enum in `src/common/types.ts`
- Update the `ALL_SCALES` const in the same file
- Update the `calculateSpriteWidth()` function in `src/panel/basepettype.ts`
- Update the `calculateBallRadius()` function in `src/panel/main.ts` and `calculateFloor()` the calculate floor is the number of pixels in the Y axis that the pets need to walk, depending on the background. 
- Scale down all foreground and background images with new names (could probably script this)
