### ISSUE TITLE
Cat assets violate seetingswarm's license

### ISSUE THREAD

**Issue by brendencallahan** [tonybaloney/vscode-pets#395]
Hi, I just wanted to inform you that you most likely do not have permission to use seethingswarm's assets in this way. (the cat assets). This was just brought up in a repo for a similar plugin in neovim (https://github.com/giusgad/pets.nvim/issues/25).

The crux of the issue is that you cannot freely distribute the cat assets which you seem to be doing in the media/cat folder.

The communication in the screenshot of the attached issue happened here (https://seethingswarm.itch.io/catset). From the top of his website, "Feel free to use for commercial projects and modify the character if needed. Please use SeethingSwarm If you want to credit me. Please do not resell the assets individually. Thank you!"

Please feel free to close, if I am missing the mark here.

**Comment by tonybaloney** [comment]
Thanks for bringing this to my attention. I did pay for the assets, read the terms and credit the author. I thought the terms were referring to making the sprite sheets or the whole package available. This plug-in uses compressed gifs based on the original assets but I will have to remove them from this repository and bundle them in when packaging the extension

**Comment by brendencallahan** [comment]
Of course! I just wanted to make sure plugin authors and this artist were on the same page, so thank you for discussing this respectfully. I mentioned on the artist's itch.io page that they should probably make their expectations more clear. I honestly wasn't sure of them until they were very explicitly stated. 

Bundling them in sounds like a perfect solution! Thanks again for taking this in stride and best of luck going forward. Love your work by the way, especially this plugin!

**Comment by tonybaloney** [comment]
I've rewritten the git history to drop copies of the assets
