### ISSUE TITLE
no need for another panel

### ISSUE THREAD

**Issue by Milo123459** [tonybaloney/vscode-pets#4]
iirc, you dont need another panel to add the pets, it could be a setting that whenever you open a file you see it at the bottom of the file, like the pet panel but just built in to the bottom of your file. would be very cool.

also this extension is amazing, it increases my productivity

**Comment by tonybaloney** [comment]
Hi.

This is how I initially started developing this extension but couldn't get it to work. VS Code limits what you can do in an extension. For custom UI (like the graphics this extension uses), you need to render a web view.
For native controls, you have to use the builtin UI toolkit, which is mostly dropdown, menu and such like (no cats).

I'd be happy to look at any samples for anyone who's done this before. 

I've seen some which hack the background of the editor panel and draw a single graphic in there, but this needs access to the whole DOM

**Comment by Milo123459** [comment]
Sadly I've never done it but it's definitely hackable!

**Comment by Phosphorus-M** [comment]
Yeah I used in Atom an extension called powermode but in VS Code the extensión doesn't work how should. The same problem, the extensions need access to the DOM but it's impossible at this moment in VS Code.

**Comment by Milo123459** [comment]
Oh, if it isn't possible then this should probably be an issue in VSCode?

**Comment by quentincaffeino** [comment]
I think this is rather a design choice to disallow modules to mess with the view of the code directly.
Powermode mentioned above uses TextEditorDecorations api which is also very limited to what it can do from my understanding.

**Comment by Milo123459** [comment]
Ah, I've seen something that displays an anime character in the bottom right. I hate anime but let me try find it.

**Comment by quentincaffeino** [comment]
This one? https://github.com/ezshine/vscode-rainbow-fart-waifu

**Comment by Milo123459** [comment]
Yes, it disgusts me 😂

On another note, it does what I *think* this extension needs.

**Comment by quentincaffeino** [comment]
Ok so I went through the code and found that it doesn't render image using vscode. It uses different executable process and communicates with it via sockets.

**Comment by Milo123459** [comment]
Will that work in this case?

**Comment by quentincaffeino** [comment]
Yeah it would but it would require to write external application for each os, not sure everyone would want to install something extra

**Comment by tonybaloney** [comment]
> This one? https://github.com/ezshine/vscode-rainbow-fart-waifu

I did read the source of that extension (also 😬) , it’s the one I was referring to which hacks the background of the page. iIRC it sets the background image of the editor tag to the graphic. It’s definitely not supported by VS code and it’s quite tricky to keep stable

**Comment by quentincaffeino** [comment]
@tonybaloney where did you find it setting the bg? Readme states that to display image you need to download external application which I guess renders graphics in a completely separate window.

**Comment by Milo123459** [comment]
Aww, let me know how I can help and I'll be sure to!

**Comment by ImedAdel** [comment]
This is a stretch and definitely out of scope, but would you consider making an Electron (or Tauri, for smaller size) app that just displays a hovering cat on the screen? :love_letter:

**Comment by Hobart2967** [comment]
Isn't there any possibility to get the handle of the text editor DOM element? So you could attach your webview to it's parent, making it position relative, full height and width, and then add 

pointer-events: none;

This would require adapting the mouse-over interaction with the cat though.

**Comment by quentincaffeino** [comment]
Webview in vscode is very similar to iframe and there's no possibly to reach to parent context from child one that I know of.

**Comment by tonybaloney** [comment]
> @tonybaloney where did you find it setting the bg? Readme states that to display image you need to download external application which I guess renders graphics in a completely separate window.

it was this extension https://github.com/shalldie/vscode-background I think it works by rewriting the CSS on disk for VS Code and injecting custom images (yikes!)

**Comment by Milo123459** [comment]
Whatever works works.. Except in this case you can't inject gifs in CSS.. well, I don't think at least.

**Comment by quentincaffeino** [comment]
@Milo123459 while you could get gifs as a bg, problem would be this extension gives much more features that would be possible to make with css.

**Comment by Milo123459** [comment]
Yes

**Comment by Milo123459** [comment]
> This is a stretch and definitely out of scope, but would you consider making an Electron (~or Tauri, for smaller size~ _doesn't support frameless windows_) app that just displays a hovering cat on the screen? 💌

Actually @ImedAdel they do: https://github.com/tauri-apps/tauri/issues/1340#issuecomment-793754044

**Comment by quentincaffeino** [comment]
@Milo123459 It wasn't released yet from what I see on a project board.

**Comment by Milo123459** [comment]
Not released but works!

**Comment by Milo123459** [comment]
Any more ideas on this?

**Comment by Milo123459** [comment]
I think I might have some ideas on how I can get this done and make a pr for it.. I'll keep you posted

**Comment by tonybaloney** [comment]
Released the explorer option in 1.1.0

**Comment by tonybaloney** [comment]
Closing this issue for now. I know some folks want the pet to wonder around the editor window, but thats simply not possible with the extension API in vscode

**Comment by Milo123459** [comment]
Has this changed at all recently? Is it possible?
