### ISSUE TITLE
Copy the current pet setup to another window

### ISSUE THREAD

**Issue by WKL10086** [tonybaloney/vscode-pets#403]
**Please describe your idea.**
I like my current pet setup, including the pet type, colour. I would love to use the same setup in another window. However, it is tedious to edit in another window and I want to complete it through copy and paste quickly.

**Describe how the idea would be helpful**
It reduces many steps to reproduce the same setup in another window.

**Additional context**

**Comment by Harry-Hopkinson** [comment]
You should be able to use the Export and Import Pet Command, see #308
