### ISSUE TITLE
a pet rock

### ISSUE THREAD

**Issue by myloooon** [tonybaloney/vscode-pets#42]
i think it would be really cool if there could be a pet rock. i've attached some concept art i workshopped for a couple hours, in case you'd like to see it. hope you enjoy let me know if you need any more info
<img width="375" alt="pet-rock-version-FINAL" src="https://user-images.githubusercontent.com/60547888/114832961-b4dc7700-9d94-11eb-8a5a-f49d5493b81d.png">

**Comment by tonybaloney** [comment]
thanks for the suggestion @myloooon I have some questions though if this were to be implemented:

1. If you poke the rock with the mouse, how should it respond?
2. Would the rock chase the ball when thrown?
3. What possible states and animations could be considered for the rock?
4. Would the rock come in different colours?

Thanks

**Comment by myloooon** [comment]
Hi Mr. Baloney,

1.) like a real small rock is often known to do, it might wiggle slightly but otherwise not do much else!
2.) i think it would like to very much but it may not be the fastest at it. maybe it could chase it, but it can only move about a pixel per minute or two?
3.) some states could include resting, dormant, stationary, lounging, and relaxing, just off the top of my head. some moods/animations could include neutral, stone-faced, or even blank! the possibilities are endless
4.) for sure! going off of the few real-life rocks i've seen, they can look pretty different from time to time and sometime have colors like gray or medium gray or dark gray or british grey or red-ish or speckled, so i think those could be considered as possible palettes

Regards,
myloooon

**Comment by TheMoonDawg** [comment]
I'm personally a fan of the rock doing absolutely nothing and just sitting there dormant for all of eternity.
