### ISSUE TITLE
Eliminate code duplication in pets module

### ISSUE THREAD

**Issue by rlszabo** [tonybaloney/vscode-pets#423]
Dear Developer,

We are a group of four Computer Science Master students at the TU/e (Technische Universiteit Eindhoven). For a course on software evolution we had chosen to study your project in detail, and as such have performed some analysis on it (guided by an assignment).  This analysis has lead us to possible restructurings of your project, and we would like to share these ideas with you. For example, during code duplication analysis we found that the "Pets" module carries the highest amount of code clones. 
We would like to propose developing a modular system that defines animation sequences in bulk for the pets, with the ability to expand on them if needed. This would eliminate long amounts of duplicate code in this module, and we hope this would make the project easier to maintain in the future. 
Please note that you are in no way obliged to do so, though we do hope you might have some thoughts on our ideas. If you are indeed interested, please let us know. 

Kind regards

**Comment by tonybaloney** [comment]
> "We would like to propose developing a modular system that defines animation sequences in bulk for the pets, with the ability to expand on them if needed."

Please can you give an example of what you mean. 

Reducing duplicatative code is a tradeoff between readability and reusability.

**Comment by tonybaloney** [comment]
And yes I would be happy to help your research

**Comment by rlszabo** [comment]
Generally our idea is to use a pull-up refactoring technique to generalize the sequences defined for the pets within the pets module. This might make it easier to add new behavior for pets & pet subgroups in the future. You are correct that this presents a trade-off between readability and reusability.
An example would be that the full sequence defined for Clippy is the same as that of the Cockatiel (and others). We can compile a new design soon and would like if you could offer your opinion on it, if only to benefit the content of our final project.
