### ISSUE TITLE
Spawn pet functionality does not work in WSL 2 (Ubuntu 20.04.6 LTS).

### ISSUE THREAD

**Issue by Hugorc10** [tonybaloney/vscode-pets#460]
**Describe the bug**
When I click on the 'Spawn additional pet' button the pet window opens and closes quickly.

**Additional context**
This bug is occurring in vscode-pets version 1.24.0. Downgrading to version 1.22.0 the bug no longer occurs.
I'm using WSL 2 with Windows 11 in its latest version.

![image](https://github.com/tonybaloney/vscode-pets/assets/26443693/e24f4b49-dc65-4063-9a9e-bc96de2a424e)
![image](https://github.com/tonybaloney/vscode-pets/assets/26443693/2ef7fc02-d4af-418c-8f31-30ec16216052)

**Comment by shlomogo** [comment]
Experiencing the same thing, rollback to 1.22 works.
