### ISSUE TITLE
Shows undefined when no pets to remove

### ISSUE THREAD

**Issue by PraneshBalasubramaniam** [tonybaloney/vscode-pets#470]
**Describe the bug**
When no pets are there to remove, the `Select the pet to remove` dropdown shows undefined

**Screenshots**

![image](https://github.com/tonybaloney/vscode-pets/assets/44346322/96b7102e-0f0a-4c7f-a4e4-80744aad796a)

**Comment by tonybaloney** [comment]
This would be a great issue for someone to fix in Hacktoberfest. Thanks for the report

**Comment by PraneshBalasubramaniam** [comment]
can I create PR I have a fix for it. we have to show empty dropdown when no pets are available, right ?

**Comment by tonybaloney** [comment]
I think it should show an error message and no drop down. Just cancel the task. An empty drop down would be confusing as well. PRs welcome
