### ISSUE TITLE
Bug when creating new type of pets

### ISSUE THREAD

**Issue by dntfindmel** [tonybaloney/vscode-pets#485]
Hey! I can't create new pets and when I try to create a new one in some place (like a snake in the forest)  the extension just create the forest with nothing inside. I can't delete the invisible pet too.

![screenshot](https://github.com/tonybaloney/vscode-pets/assets/120610288/0e274a9c-1d0e-4a4b-a83a-aaaae4149974)

**Comment by tonybaloney** [comment]
Please update to 1.25.1, this should be fixed and you can use the `+` button to add new pets
