### ISSUE TITLE
Spawning additional pets

### ISSUE THREAD

**Issue by jt326** [tonybaloney/vscode-pets#487]
**Describe the bug**
When attempting to spawn an additional pet, the drop-down menu displaying the options (cat, dog etc.) flashes up then immediately disappears. The plus button in the pets window also does not work, although the ball does. I uninstalled the extension, restarted vscode then reinstalled the extension. It has remembered the theme I chose, but there is no cat and I can't add any pets. 

**Screenshots**
Please send screenshots of the developer console (Right-click > Inspect > Console) on the pages where the bug is occurring.

**Additional context**

**Comment by visiongirles** [comment]
Have the similar issue. I manually created json with some pets options and imported them, so I can have some pets while this bug occurs.

**Comment by n-xsi** [comment]
Same issue
@visiongirles How did you do that? I tried exporting a pet list from another instance I had but it created an empty array JSON file.

**Comment by visiongirles** [comment]
1. I've created a cats.json manually as follows: 
`[
  {
    "color": "lightbrown",
    "type": "cat",
    "size": "nano",
    "name": "Foo"
  },
  {
    "color": "black",
    "type": "cat",
    "size": "nano",
    "name": "Night"
  },
  {
    "color": "white",
    "type": "cat",
    "size": "nano",
    "name": "Yarik"
  }
]
`

Save it anywhere you want.
2. Press `ctr+shift+p` for command panel in Visual Studio Code. Type: `Pet coding: import pet list` and choose the file you created earlier.

If you need to make some changes:
1. Delete all your current pets. If you don't, they will be duplicated. If you need to delete a pet, use remove pet (garbage icon) on the panel or again `ctr+shift+p`  and type `remove pet`
2. Edit json and import it again.
3. 
Hope it helps, let me know if you have any questions.

**Comment by n-xsi** [comment]
@visiongirles 
It worked!!
Thank you for the steps

**Comment by tonybaloney** [comment]
Hello!

I need some help working out where the problem is to fix it?

What VS Code version are you using?
What version of the extension do you have installed?
Are you running windows, linux or Mac?
Are you using another language in VS Code?

**Comment by visiongirles** [comment]
Hello. From my side as follow:

What VS Code version are you using? **1.84.0**
What version of the extension do you have installed?  **v1.25.0**
Are you running windows, linux or Mac? **VSC on Windows, by WSL:Ubuntu environment inside VSC**
Are you using another language in VS Code? **I use English language**

**Comment by tonybaloney** [comment]
> Hello. From my side as follow:
> 
> What VS Code version are you using? **1.84.0** What version of the extension do you have installed? **v1.25.0** Are you running windows, linux or Mac? **VSC on Windows, by WSL:Ubuntu environment inside VSC** Are you using another language in VS Code? **I use English language**

Ah thank you! Now I can reproduce this and I've figured out what the issue is.. Will try and ship a patch asap

**Comment by tonybaloney** [comment]
Please update the extension to the latest version (1.25.1) shortly when it is available in the marketplace
