### ISSUE TITLE
New pet dialog box disapearing

### ISSUE THREAD

**Issue by willmil11** [tonybaloney/vscode-pets#489]
When i click spawn new pet the dialog pox disapears imediatly after being opened i managed to get 1 pet hardly by clicking where cat is going to be while clicking with the touchpad the spawn button but thats hard pls fix (Note: After selecting pet type the next dialog boxes are fine)

**Comment by alexlatch** [comment]
this is happening to me too

**Comment by willmil11** [comment]
So what do we do

**Comment by tonybaloney** [comment]
Please share what version of VS Code you have and what version of the extension you have installed?

**Comment by tonybaloney** [comment]
Please update the extension to the latest version (1.25.1) shortly when it is available in the marketplace
