### ISSUE TITLE
Can't change pet type

### ISSUE THREAD

**Issue by LucasColas** [tonybaloney/vscode-pets#492]
Hello,
I'm using visual sutdio code with version 1.83.1. 
Unfortunately I can't change the pet type.

![bug pet type](https://github.com/tonybaloney/vscode-pets/assets/51634013/313bcce1-dcb3-4240-9675-e53d063418a3)

**Comment by tonybaloney** [comment]
There are no green cats (unless there was an unfortunate incident with some paint).

You can add a custom pet using the `+` button in the VS Code pets window and set the available colours from there

**Comment by LucasColas** [comment]
The `+` button doesn't work either. When I click on the `+` button the window to select a pet disappears instantly.

**Comment by tonybaloney** [comment]
Make sure you've updated to the latest version (1.25.1) and restarted vs code
