### ISSUE TITLE
Pet won't respawn

### ISSUE THREAD

**Issue by viewolfe321** [tonybaloney/vscode-pets#493]
**Describe the bug**
When I click "spawn additional pet", a menu to pick what pet I want appears for a millisecond, then vanishes. This happens when I hit the "+" symbol, as well as when I type ">pets" and then click "spawn an additional pet" from the search in VScode. 

**Screenshots**
![catmissing](https://github.com/tonybaloney/vscode-pets/assets/106555729/39d84eb1-be49-41f2-bee7-76a0bfefb9cf)
(I have no idea if you can see that screenshot, but hopefully it works. I am new to github, sorry.)

**Additional context**
I tried changing things around in settings, uninstalling and reinstalling, turning my computer on and off again. 
I am heartbroken over the loss of my cat, I hope this can be fixed...

**Comment by MelissaNwk** [comment]
1. Create wherever you want a pet_category.json file manually (e.x. pet_category = dog.json):

`[   { "color": "black", "type": "dog", "size": "nano", "name": "Coco"   },   { "color": "white", "type": "dog", "size": "nano", "name": "Lucy"   } ] `

3. Open the command panel (ctrl / cmd ⌘+ shift + P) in vsc and select "Pet Coding: Import pet list"
4. Select the created .json file
5. No more heartbreaks

**Comment by MelissaNwk** [comment]
@poedude5229 what's the problem?

**Comment by tonybaloney** [comment]
What version of VS Code is everyone using?

**Comment by tonybaloney** [comment]
This is fixed in 1.25.1, please update the extension
