### ISSUE TITLE
Can't add any pets

### ISSUE THREAD

**Issue by poedude5229** [tonybaloney/vscode-pets#494]
After removing the cat that defaults to, I cannnot add any pet. The menu to add a pet appears for a split second at the top of the screen and nothing happens, even after enabling every part of your extension.

**Comment by tonybaloney** [comment]
What version of VS Code are you using?
What version of VS Code Pets do you have installed?

**Comment by tonybaloney** [comment]
Please update the extension to the latest version (1.25.1) shortly when it is available in the marketplace
