### ISSUE TITLE
Interaction between multiple pets

### ISSUE THREAD

**Issue by eroecher** [tonybaloney/vscode-pets#50]
Interactions between multiple pets (e.g. playful fighting) would be great ;)

**Comment by tonybaloney** [comment]
I agree it would be a nice feature. I'm not sure yet to what depth this would work, i.e.,
Should the dog and crab interact differently than the dog and cat? What would two cats do? Would two cats get to know each other over time? It would be distracting to have a big sequence every time they pass, which is often. 
I think it'd also be fun for the animals to chase one another

**Comment by eroecher** [comment]
Yeah, custom animation for each type of animal would be the most life like thing, but it also adds a lot of complexity. Maybe it's easier to start with interactions that can be reused with any pair of animals like a type of looking at each other. Every pet gets it's own looking animation and everytime two pets meet, there is a chance for an interaction. 
I suppose you could use the same playful fighting animation for cats and dogs, but I am unsure what a playful fighting snake looks like ;)
One other thing that I think would work is having a sleeping animation like someone suggested and a sleeping animal is excluded from interaction animations. This is a clever way to prevent animations from repeating themselves too often.
Animals chasing each other is a great idea. This doesn't require additional animations and could start with a certain probability after two animals looked at each other.

**Comment by tonybaloney** [comment]
This is already implemented. I forgot to comment on the issue
