### ISSUE TITLE
Broken image

### ISSUE THREAD

**Issue by HelveticaScenario** [tonybaloney/vscode-pets#51]
I set my pet to a grey cat and it showed up as a broken image, and now even though I added a brown cat the broken image cat wont go away.

**Comment by tonybaloney** [comment]
I just had the same issue. In the logs it was referring to the previous version of the extension.

Try reloading the window and seeing if that fixes the bug, otherwise I'll have to raise it with the vscode team

**Comment by computergnome99** [comment]
![image](https://user-images.githubusercontent.com/55407248/119985298-768bc780-bf90-11eb-9d8d-bba2952bf2ae.png)

Same issue. I went to spawn a dog but before I could choose the color the command line closed and the broken image spawned.

**Comment by computergnome99** [comment]
Wouldn't be such an issue if I could de-spawn pets. That might be the simple "band-aid" solution.

**Comment by PouekDEV** [comment]
![image](https://user-images.githubusercontent.com/64737924/145952395-1862828f-d1e9-41d2-9e68-41a906fd5506.png)
Same issue. It's kind of annoying

**Comment by shafiqfikri** [comment]
![image](https://user-images.githubusercontent.com/39353080/146304775-21315a1e-4928-4c4d-991f-3fe1e64d30da.png)
Same issue here. I think I also set it to grey cat before it bugged out.
Reload & reinstalling doesn't work for me.

**Comment by tonybaloney** [comment]
Fixed in 1.9.2. Cats and dogs can only be brown or black. The settings would let you type anything. Now it will default to brown.
