### ISSUE TITLE
more place for pets across all tabs and complete VS Code?

### ISSUE THREAD

**Issue by GumblCode** [tonybaloney/vscode-pets#545]
Can I give my pets more flowing out so that they can walk around in my complete open VS code panel and tabs?
Not only Panel and explorer position

it would relax the excitations when coding and it's better for work flow and new mindset 

I hope it is not a big effort

**Comment by Harry-Hopkinson** [comment]
Unfortunately, due to limitations with the current vscode API it is currently not possible to achieve this.

See https://github.com/tonybaloney/vscode-pets/issues/250 for more information.
