### ISSUE TITLE
let the pets move around in the code files

### ISSUE THREAD

**Issue by eymeen** [tonybaloney/vscode-pets#550]
**Please describe your idea.**
it would be great if the pets move between the letters without annoying the user. And also when using frameworks (huge directory tree) there would be little to no place for the pets sometimes, it will be better if they are on top of the code in a smooth way

**Describe how the idea would be helpful**
as I said, it will not take too much place in the grid and it will be more fun to have them inside the code file

**Additional context**
1. there shouldn't be user-select, it will be too annoying
2. it should be optional 

unrelated additional features:
3. pet sounds
4. pet label with names

**Comment by tonybaloney** [comment]
this is not possible. See #250
