### ISSUE TITLE
Name cursor should be per petType

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/vscode-pets#56]
In the state there's a `petNumber` variable which represents the number of created pets. this is used to pick the next name in the names.ts file, but its global, so if you have 3 cats and add a Totoro it'll name it the 4th name in the Totoro list, which is silly because it should be the first (Totoro)

**Comment by JING1201** [comment]
I can take on this one! Is anyone else working on this?

**Comment by tonybaloney** [comment]
@JING1201 yes please!
