### ISSUE TITLE
Pet's image is broken

### ISSUE THREAD

**Issue by johnadan** [tonybaloney/vscode-pets#64]
![image](https://user-images.githubusercontent.com/37522436/122696214-2e04b880-d275-11eb-9422-d657656df5e3.png)

Ever since installing the extension, images of pets won't show up.

**Comment by tonybaloney** [comment]
Please try reloading the window and see if this fixes it. If not, change to another pet.

**Comment by johnadan** [comment]
Hi Tony! Adding a new pet works! Thanks!
