### ISSUE TITLE
Overlay pets on files.

### ISSUE THREAD

**Issue by cscott20** [tonybaloney/vscode-pets#71]
I would love if this extension could overlay pets on whichever file is currently open!

**Comment by tonybaloney** [comment]
duplicate of https://github.com/tonybaloney/vscode-pets/issues/4

The answer sadly is no,

**Comment by cscott20** [comment]
Any reason? Is it not easy / possible to implement?

**Comment by tonybaloney** [comment]
It's not possible. VS code doesn't provide an API for anything like that. We're constrained to the panel
