### ISSUE TITLE
Pets inside existing vscode tabs

### ISSUE THREAD

**Issue by AlanBlanchet** [tonybaloney/vscode-pets#73]
Hello,

Firstly I'd like to say that I love the idea behind this extension.
I find it hilarious !

That being said, I'd love to be able to watch the pet while I program in my vscode window.

For instance take my `.scss` file :
![image](https://user-images.githubusercontent.com/22567306/145183782-6aefcbbb-8573-44ec-96d3-a2fc9a24dba7.png)

I'd love to see the pet here, at the bottom. Would that be possible ?

Many thanks and good luck to the futur of this extension !

**Comment by ErnstStavroBlofeld** [comment]
Great idea! It would be amazing if pets could walk on/in status bar.

**Comment by tonybaloney** [comment]
See #71 (the short answer is this isn't possible)
