### ISSUE TITLE
Pet interaction "swipe" animates too many times.

### ISSUE THREAD

**Issue by Tarang74** [tonybaloney/vscode-pets#78]
Hey!

Would it be possible to animate the pet interaction "swipe" fewer times? 
The pet continues to interact 8-9 times even after moving my mouse cursor away from the pet.

Thanks!

**Comment by TheMoonDawg** [comment]
Yeah, I was worried my animation got stuck. He swipes for another 2-3 seconds after you move your cursor away.

**Comment by tonybaloney** [comment]
fixed in 1.9.2
