### ISSUE TITLE
Add To Open VSX Registry

### ISSUE THREAD

**Issue by UCYT5040** [tonybaloney/vscode-pets#82]
Adding this extension here allows users of VScode that do not use a Microsoft managed version, such as Gitpod.

https://open-vsx.org/

**Comment by tonybaloney** [comment]
Thanks, I always attach the VSIX to the release tag if people need to download it separately https://github.com/tonybaloney/vscode-pets/releases/tag/1.9.1

**Comment by zalsader** [comment]
Hello! The last few tags do not have a vsix. Could you please make sure it is automated? Also, someone already tried to [publish your extension there](https://open-vsx.org/extension/tonybaloney/vscode-pets), but it's an outdated version.

**Comment by tonybaloney** [comment]
I just added the VSIX to the latest release. https://github.com/tonybaloney/vscode-pets/releases/tag/1.28.0
The release process isn't automated, although GitHub Actions generates the VSIX as a build artifact I still write the release notes and test it manually
