### ISSUE TITLE
Yellow Medium Dog not loading properly

### ISSUE THREAD

**Issue by Turkey-Lurkey** [tonybaloney/vscode-pets#84]
Instead of a dog, I get an interactive broken image icon. I don't mind it... But thought you should know.

![file_pet](https://user-images.githubusercontent.com/64878230/146134375-d794d629-6152-49a4-8bbe-9dc1677d4ab7.JPG)

**Comment by tonybaloney** [comment]
dog should only be brown or black, the code should default back to brown if you pick another color. I'll fix that up

**Comment by Turkey-Lurkey** [comment]
Ah I guess I failed to read the documentation. Classic. Thank you

**Comment by tonybaloney** [comment]
fixed in 1.9.2
