### ISSUE TITLE
Support Visual Studio ?

### ISSUE THREAD

**Issue by Robertkq** [tonybaloney/vscode-pets#91]
I really like this extension, and I am really jealous that I can't use this in Visual Studio,
could support for Visual Studio be added ?

**Comment by Harry-Hopkinson** [comment]
I am uploading it to the visual studio store as a test. If it works with the native source code I will delete it so @tonybaloney can publish it. As the project is his.

**Comment by Harry-Hopkinson** [comment]
Try this -> https://marketplace.visualstudio.com/items?itemName=HarryHopkinson.visual-studio-pets
I do not have visual studio installed so can you report back if the extension is working

**Comment by tonybaloney** [comment]
this certainly won't work. the VSIX is a ZIP format, but the contents are specific to VS Code. Visual Studio extensions are written in c# and compiled as binary libraries. 
VS Code extensions are JavaScript and loaded as runtime components

**Comment by Harry-Hopkinson** [comment]
Ah okay I was experimenting
