### ISSUE TITLE
I have added several pets, how can I delete one?

### ISSUE THREAD

**Issue by rubenmacias2** [tonybaloney/vscode-pets#96]
I have added several pets, how can I delete one?

**Comment by Harry-Hopkinson** [comment]
I do not think you can remove pets. You can only reset pets from the workspace

**Comment by Harry-Hopkinson** [comment]
I am working on a new command to remove a selected pet as the send to farm alternate does not seem to work.

**Comment by Harry-Hopkinson** [comment]
The Reset Pets command does not seem to be working, but I fixed it in this PR #93

**Comment by Harry-Hopkinson** [comment]
@tonybaloney can you release the new changes, from which this issue is fixed?

**Comment by tonybaloney** [comment]
Use the `vscode-pets.delete-pet` command from the command pallets. Added in 1.12.0
