### ISSUE TITLE
Pet has a stroke

### ISSUE THREAD

**Issue by asportnoy** [tonybaloney/vscode-pets#97]
If you spam balls, the pet will eventually start to have a stroke. The ball speed also gets turned up waaaaay too high.

https://user-images.githubusercontent.com/14863373/155206330-2c5abab0-8fa5-45a5-8f39-09f46e45f025.mp4

**Comment by Harry-Hopkinson** [comment]
I will have a look at this

**Comment by tonybaloney** [comment]
Lol. Poor thing doesn't know which one to chase.

**Comment by Harry-Hopkinson** [comment]
@tonybaloney where is the throw ball code - as I am working on this issue, I have tried rewriting the throwBall command as stated in this switch statement called by the webview after running the vscode-pets.throw-ball command. I have even tried removing this command altogether but the ball still throws. I was just wondering where is the code to throw the ball as seen in the webview during initiation of the command

**Comment by tonybaloney** [comment]
Fixed in #167
